# Generated by Django 2.0.1 on 2018-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('password', models.TextField(default='')),
            ],
        ),
    ]
