# Generated by Django 2.0.1 on 2018-02-26 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='datetime',
            new_name='destination_time',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sent_time',
        ),
        migrations.AddField(
            model_name='letter',
            name='write_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
