# Generated by Django 2.0.1 on 2018-02-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_auto_20180226_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('R', 'Readed'), ('N', 'Not Readed')], default='N', max_length=1),
        ),
    ]
