# Generated by Django 2.0.1 on 2018-02-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_letter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('Readed', 'Readed'), ('Not Read', 'Not Read')], default='Not Read', max_length=1),
        ),
    ]
